import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

const articles=[
{slug:"hva-bor-en-god-bedriftsnettside-inneholde",title:"Hva bør en god bedriftsnettside inneholde?",intro:"En god bedriftsnettside skal gjøre det enkelt å forstå hva dere tilbyr, hvorfor dere er relevante og hva kunden bør gjøre videre."},
{slug:"hvorfor-vises-ikke-nettsiden-pa-google",title:"Hvorfor vises ikke nettsiden på Google?",intro:"Synlighet handler om mer enn å ha en nettside. Struktur, innhold, teknisk SEO og relevans spiller sammen."},
{slug:"hvor-mye-koster-en-nettside",title:"Hvor mye koster en nettside?",intro:"Prisen bør henge sammen med hva nettsiden skal oppnå. Her er hva som faktisk påvirker kostnaden."},
{slug:"hvordan-fa-flere-henvendelser-fra-nettsiden",title:"Hvordan få flere henvendelser fra nettsiden?",intro:"Flere besøk er ikke nok. Nettsiden må gjøre det lett for riktig kunde å ta neste steg."}
];
const services={
websites:{title:"Nettsider som gjør jobben sin",desc:"Vi designer og bygger nettsider som gjør bedriften enklere å forstå, finne og velge."},
seo:{title:"SEO som bygger synlighet over tid",desc:"Vi bygger en søkestrategi rundt spørsmål og behov kundene faktisk har."},
"digital-marketing":{title:"Digital markedsføring som henger sammen",desc:"Kampanjer, innhold og digitale kanaler bygget rundt et tydelig mål."},
branding:{title:"En merkevare folk husker",desc:"Visuell identitet og kommunikasjon som gjør bedriften tydeligere og mer gjenkjennelig."}
};
const mail="mailto:jelassi@smartsvar.no?subject=Uforpliktende%20vurdering%20Cidea%20Marketing";
function Meta({path}){useEffect(()=>{let title="Cidea Marketing — Gjør bedriften vanskelig å ignorere.",desc="Nettsider, branding, SEO og digital markedsføring for bedrifter.";const k=path.split("/").filter(Boolean)[0];if(services[k]){title=services[k].title+" | Cidea Marketing";desc=services[k].desc}const a=articles.find(x=>x.slug===path.split("/")[2]);if(a){title=a.title+" | Cidea Marketing";desc=a.intro}if(path==="/blog")title="Blogg om digital markedsføring | Cidea Marketing";document.title=title;document.querySelector('meta[name="description"]')?.setAttribute("content",desc);document.querySelector('link[rel="canonical"]')?.setAttribute("href","https://cideamarketing.com"+path)},[path]);return null}
function Header({lang,setLang}){return <header><a className="logo"href="/">cidea<span>marketing</span></a><nav><a href="/websites">Nettsider</a><a href="/branding">Branding</a><a href="/seo">SEO</a><a href="/digital-marketing">Digital markedsføring</a><a href="/blog">Blogg</a></nav><div className="actions"><button onClick={()=>setLang(lang==="no"?"en":"no")}>{lang==="no"?"EN":"NO"}</button><a className="navCta"href={mail}>{lang==="no"?"Få en vurdering →":"Get an assessment →"}</a></div></header>}
function Work(){return <section className="section work"><div className="intro"><p className="eyebrow">SELECTED WORK</p><h2>Noen av tingene vi bygger.</h2><p>Design skal ikke bare se bra ut. Det skal gjøre en jobb.</p></div><div className="workGrid"><a href="/websites" className="project projectA"><div className="mock browser"><div className="browserBar"><i/><i/><i/></div><div className="mockHero"><span>ATELIER / 01</span><strong>Form.<br/>Function.<br/>Identity.</strong></div></div><small>01 / DIGITAL EXPERIENCE</small><h3>Et digitalt uttrykk med en tydelig idé.</h3></a><a href="/branding" className="project projectB"><div className="mock brand"><span>STUDIO</span><b>FORM</b><em>Brand identity / 2026</em></div><small>02 / BRAND IDENTITY</small><h3>En identitet som tåler å bli sett.</h3></a><a href="/digital-marketing" className="project projectC"><div className="mock campaign"><div>MAKE<br/><b>NOISE.</b></div><span>CAMPAIGN / SOCIAL / DIGITAL</span></div><small>03 / CAMPAIGN</small><h3>En kampanje bygget rundt én klar idé.</h3></a></div></section>}
function Home({lang}){const en=lang==="en";return <><section className="hero"><div className="heroText"><p className="eyebrow">CIDEA MARKETING / DIGITAL STUDIO</p><h1>{en?"Make your business impossible to ignore.":"Gjør bedriften vanskelig å ignorere."}</h1><p className="lead">{en?"We build brands and digital experiences that make businesses easier to find, understand and choose.":"Vi bygger merkevarer og digitale opplevelser som gjør det enklere å bli funnet, forstått og valgt."}</p><div className="heroActions"><a className="button blue"href={mail}>{en?"Get an assessment":"Få en uforpliktende vurdering"} ↗</a><a className="textLink"href="#work">Se arbeidet ↓</a></div><p className="quiet">Ingen kostnad. Ingen forpliktelser.</p></div><div className="heroArt"><div className="typeStack"><span>WEB</span><span>BRAND</span><span>SEO</span><span>SOCIAL</span></div><div className="heroCard"><small>CIDEA / 01</small><strong>BUILD<br/>SOMETHING<br/><i>MEMORABLE.</i></strong><div><span>STRATEGY</span><span>DESIGN</span><span>GROWTH</span></div></div></div></section>
<Work/>
<section className="section capabilities"><div className="intro"><p className="eyebrow">WHAT WE DO</p><h2>Én digital tilstedeværelse. Mange kontaktpunkter.</h2></div><div className="capGrid"><a href="/websites"><span>NETTSIDER</span><h3>Nettsider</h3><p>Digitale opplevelser bygget for å bli valgt.</p><b>Utforsk →</b></a><a href="/branding"><span>BRANDING</span><h3>Branding</h3><p>En identitet folk kjenner igjen og husker.</p><b>Utforsk →</b></a><a href="/seo"><span>SEO</span><h3>SEO</h3><p>Synlighet som bygger seg over tid.</p><b>Utforsk →</b></a><a href="/digital-marketing"><span>DIGITAL MARKEDSFØRING</span><h3>Digital markedsføring</h3><p>Kampanjer og innhold som skaper etterspørsel.</p><b>Utforsk →</b></a></div></section>
<section className="section philosophy"><div className="statement"><p className="eyebrow">THE IDEA</p><h2>Det handler ikke om å være overalt. Det handler om å være tydelig.</h2></div><div className="philosophyGrid"><p>En god digital tilstedeværelse har en rød tråd fra første inntrykk til første henvendelse.</p><div><span>FORSTÅ</span><strong>Forstå</strong><p>Hva skal kunden forstå på fem sekunder?</p></div><div><span>SKAPE</span><strong>Skape</strong><p>Hvordan skal merkevaren oppleves?</p></div><div><span>FORBEDRE</span><strong>Forbedre</strong><p>Hva kan bli tydeligere, raskere eller mer relevant?</p></div></div></section>
<section className="section approach"><div className="intro"><p className="eyebrow">OUR APPROACH</p><h2>Strategi. Design. Resultater.</h2></div><div className="approachList"><div><span>FORSTÅ</span><h3>Forstå</h3><p>Vi starter med virksomheten, markedet og menneskene dere ønsker å nå.</p></div><div><span>SKAPE</span><h3>Skape</h3><p>Vi gjør strategien synlig gjennom design, innhold og digitale opplevelser.</p></div><div><span>FORBEDRE</span><h3>Forbedre</h3><p>Vi ser på hva som fungerer og forbedrer det som kan bli bedre.</p></div></div></section>
<section className="section audit"><div><p className="eyebrow">NO SALES PITCH</p><h2>Hva kunne vært bedre?</h2><p>Vi vurderer nettsiden, merkevaren og den digitale tilstedeværelsen din og peker på de viktigste forbedringsmulighetene.</p><a className="button dark"href={mail}>Få en uforpliktende vurdering →</a><small>Ingen kostnad. Ingen forpliktelser.</small></div><div className="auditNotes"><span>WEBSITE</span><span>BRAND</span><span>SEO</span><span>SOCIAL</span><span>CONVERSION</span></div></section>
<section className="section journal"><div className="intro"><p className="eyebrow">JOURNAL</p><h2>Vi skriver om ting folk faktisk lurer på.</h2></div><div className="articleGrid">{articles.slice(0,3).map(a=><a href={"/blog/"+a.slug}key={a.slug}><span>ARTICLE</span><h3>{a.title}</h3><p>{a.intro}</p><b>Les artikkelen →</b></a>)}</div></section>
<section className="final"><p className="eyebrow">LET'S MAKE IT CLEAR</p><h2>Hva skal kunden din se?</h2><p>Vi hjelper deg å gjøre det tydeligere hvem dere er, hva dere tilbyr og hvorfor det er verdt å velge dere.</p><a className="button dark"href={mail}>Få en uforpliktende vurdering →</a></section></>}
function Service({data}){return <section className="page"><p className="eyebrow">CIDEA MARKETING</p><h1>{data.title}</h1><p className="pageLead">{data.desc}</p><div className="serviceGrid"><article><span>STRATEGI</span><h2>Strategi</h2><p>Vi begynner med hva virksomheten trenger å oppnå.</p></article><article><span>DESIGN</span><h2>Design</h2><p>Vi gjør posisjoneringen tydelig gjennom uttrykk og opplevelse.</p></article><article><span>FORBEDRING</span><h2>Forbedring</h2><p>Vi måler, lærer og forbedrer det digitale arbeidet.</p></article></div><div className="pageCta"><h2>Få en uforpliktende vurdering.</h2><p>Ingen kostnad. Vi peker på konkrete forbedringsmuligheter.</p><a className="button blue"href={mail}>Be om vurdering →</a></div><div className="offerGrid"><article><span>START</span><h2>Website</h2><strong>Fra 15 000 NOK</strong><p>Strategi, struktur, design og implementering for en tydelig bedriftsnettside.</p></article><article><span>BRAND</span><h2>Brand Foundation</h2><strong>Fra 9 900 NOK</strong><p>En praktisk visuell grunnmur med retning for typografi, farger og merkevareuttrykk.</p></article><article><span>SEO</span><h2>SEO</h2><strong>Fra 5 900 NOK / mnd</strong><p>Løpende arbeid rundt teknisk SEO, innhold, søkeintensjon og synlighet.</p></article><article><span>GROWTH</span><h2>Digital markedsføring</h2><strong>Fra 9 900 NOK / mnd</strong><p>Strategi, innhold, kampanjer og optimalisering rundt et tydelig kommersielt mål. Annonsebudsjett kommer i tillegg.</p></article></div></section>}
function Blog({article}){return <section className="page">{article?<><p className="eyebrow">JOURNAL</p><h1>{article.title}</h1><p className="pageLead">{article.intro}</p><div className="articleBody"><p>{article.intro} En god løsning må starte med et tydelig mål, relevant innhold og en opplevelse som gjør neste steg enkelt.</p></div><a className="textLink"href="/blog">← Alle artikler</a></>:<><p className="eyebrow">JOURNAL</p><h1>Innsikt for bedrifter som vil bli tydeligere.</h1><p className="pageLead">Praktiske svar om nettsider, SEO, branding og digital markedsføring.</p><div className="articleList">{articles.map(a=><a href={"/blog/"+a.slug}key={a.slug}><span>ARTICLE</span><h2>{a.title}</h2><p>{a.intro}</p><b>Les artikkelen →</b></a>)}</div></>}</section>}
function App(){const[lang,setLang]=useState("no");const path=location.pathname.replace(/\/$/,"")||"/";<Meta path={path}/>;const key=path.split("/").filter(Boolean)[0];const article=articles.find(a=>a.slug===path.split("/")[2]);const content=path==="/"?<Home lang={lang}/>:path==="/blog"||article?<Blog article={article}/>:services[key]?<Service data={services[key]}/>:<Home lang={lang}/>;return <div className="site"><Header lang={lang}setLang={setLang}/><main>{content}</main><footer><a className="logo"href="/">cidea<span>marketing</span></a><span>Digital studio · Oslo / Norge</span><a href={mail}>Kontakt →</a></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);